compiler:
  - clang
  - gcc

os: linux
dist: trusty
sudo: required
language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential dh-make dpkg-dev libjsoncpp-dev libbotan1.10-dev libcurl4-openssl-dev libargtable2-dev libmicrohttpd-dev

before_script:
  # compile and install OnioNS-common library from source
  - git clone --branch json-rpc --recursive --depth=25 https://github.com/Jesse-V/OnioNS-common.git
  - cd OnioNS-common
  - package=tor-onions-common_$(grep -m 1 -o '(.*)' debian/changelog | cut -c 2- | rev | cut -c 2- | rev)
  - tar -czf $package.orig.tar.gz src/
  - cp -rl debian src/debian
  - cd src/
  - dpkg-buildpackage -rfakeroot -us -uc # compile into .deb
  - sudo dpkg -i ../$package\_amd64.deb  # install .deb
  - cd ../../

script:
  - package=tor-onions-server_$(grep -m 1 -o '(.*)' debian/changelog | cut -c 2- | rev | cut -c 2- | rev)
  - tar -czf $package.orig.tar.gz src/
  - cp -rl debian src/debian
  - cd src/
  - dpkg-buildpackage -rfakeroot -us -uc # compile into .deb

after_success:
  - sudo dpkg -i ../$package\_amd64.deb  # install .deb
  - sha256sum ../$package\_amd64.deb

notifications:
  email: false
  irc:
    channels:
      - "irc.oftc.net#tor-bots"
    on_success: change
    on_failure: change
    template:
      - "%{repository} (%{branch} - %{commit}) @kernelcorn %{message}"
      - "Build details : %{build_url}"
